<!DOCTYPE html>
<html lang="pl">

<head>
	<meta charset="utf-8">
	<title>Four+One Library</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="Bootstrap 3 template for corporate business" />
	<!-- css -->
	<link href="../../html/css/bootstrap.min.css" rel="stylesheet" />
	<link href="../../html/css/cubeportfolio.min.css" rel="stylesheet" />
	<link href="../../html/css/style.css" rel="stylesheet" />

	<!-- Theme skin -->
	<link id="t-colors" href="../../html/skins/default.css" rel="stylesheet" />

	<!-- boxed bg -->
	<link id="bodybg" href="../../html/bodybg/bg1.css" rel="stylesheet" type="text/css" />



</head>

<body>


	<div id="wrapper">
		<!-- start header -->
		<header>
			<div class="text-center margintop50">
				<a href="index.ftlh">   <img src="../../html/img/logo.png" alt="" width="199" height="52" /></a>

				</div>

		</header>
		<!-- end header -->

		<section id="content">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="text-center">
							<h2>Pracujemy nad tym. Zdążymy na czas!</h2>
							
							<a class="btn btn-primary" href="index.ftlh" role="button">Strona główna</a>
						</div>
					</div>
				</div>
			</div>
		</section>

		<div id="sub-footer">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="copyright">
							<p>&copy; Sailor Theme - All Right Reserved</p>
							<div class="credits">
									<!--
                    All the links in the footer should remain intact. 
                    You can delete the links only if you purchased the pro version.
                    Licensing information: https://bootstrapmade.com/license/
                    Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Sailor
                  -->
									Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
								</div>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>

	<!-- javascript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="../../html/js/jquery.min.js"></script>
	<script src="../../html/js/modernizr.custom.js"></script>
	<script src="../../html/js/jquery.easing.1.3.js"></script>
	<script src="../../html/js/bootstrap.min.js"></script>
	<script src="../../html/js/jquery.appear.js"></script>
	<script src="../../html/js/stellar.js"></script>
	<script src="../../html/js/classie.js"></script>
	<script src="../../html/js/uisearch.js"></script>
	<script src="../../html/js/jquery.cubeportfolio.min.js"></script>
	<script src="../../html/js/google-code-prettify/prettify.js"></script>
	<script src="../../html/js/animate.js"></script>
	<script src="../../html/js/jquery.countdown.min.js"></script>
	<script src="../../html/js/custom.js"></script>
	


</body>

</html>
