<!DOCTYPE html>
<html lang="pl">

<head>
	<meta charset="utf-8">
	<title>Four+One Library</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta name="description" content="Bootstrap 3 template for corporate business"/>
	<!-- css -->
	<link href="../../html/css/bootstrap.min.css" rel="stylesheet"/>
	<link href="../../html/plugins/flexslider/flexslider.css" rel="stylesheet" media="screen"/>
	<link href="../../html/css/cubeportfolio.min.css" rel="stylesheet"/>
	<link href="../../html/css/style.css" rel="stylesheet"/>

	<!-- Theme skin -->
	<link id="t-colors" href="../../html/skins/default.css" rel="stylesheet"/>

	<!-- boxed bg -->
	<link id="bodybg" href="../../html/bodybg/bg1.css" rel="stylesheet" type="text/css"/>
</head>

<body>


<div id="wrapper">
	<!-- start header -->
	<#include "header.ftlh">
		<div class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="../../html/index.html"><img src="../../html/img/logo.png" alt="" width="199"
																			  height="52"/></a>
				</div>
				<div class="navbar-collapse collapse ">
					<ul class="nav navbar-nav">
						<li class="active"><a href="../../html/index.html">Strona główna</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown"
							   data-delay="0" data-close-others="false">Biblioteka <i class="fa fa-angle-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="../../html/comingsoon.html">Wyszukaj</a></li>
								<li class="dropdown-submenu">
									<a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown">Katalog</a>
									<ul class="dropdown-menu">
										<li><a href="../../html/comingsoon.html">Książki</a></li>
										<li><a href="../../html/comingsoon.html">AudioBooki</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a href="../../html/login.html">Zaloguj/Rejestracja</a></li>
					</ul>
				</div>
			</div>
		</div>
<#include "footers.ftlh">
</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

<!-- Placed at the end of the document so the pages load faster -->
<script src="../../html/js/jquery.min.js"></script>
<script src="../../html/js/modernizr.custom.js"></script>
<script src="../../html/js/jquery.easing.1.3.js"></script>
<script src="../../html/js/bootstrap.min.js"></script>
<script src="../../html/plugins/flexslider/jquery.flexslider-min.js"></script>
<script src="../../html/plugins/flexslider/flexslider.config.js"></script>
<script src="../../html/js/jquery.appear.js"></script>
<script src="../../html/js/stellar.js"></script>
<script src="../../html/js/classie.js"></script>
<script src="../../html/js/uisearch.js"></script>
<script src="../../html/js/jquery.cubeportfolio.min.js"></script>
<script src="../../html/js/google-code-prettify/prettify.js"></script>
<script src="../../html/js/animate.js"></script>
<script src="../../html/js/custom.js"></script>


</body>

</html>
    