<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <form method="post" action="/uploader" enctype="multipart/form-data">
        <title>Upload pliku JSON</title>
        <p></p>
        <header>Awaryjne ładowanie API z pliku</header>
        <input type="file" accept="application/JSON" name="api">
        <input type="submit" name="upload" value="Upload">
    </form>
</head>
<body>

</body>
</html>