<div id="book-form-container" class="container">
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <form class="border p-5 " method="POST" action="#" enctype="multipart/form-data">


                <label for="textInput">Gatunek</label>
                <input type="text" id="textInput" class="form-control mb-4"
                       placeholder="Podaj gatunek literacki" name="genre" required>




            </form>
        </div>
    </div>
</div>